language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

before_install:
  - "mkdir -p ~/.npm"
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update

install:
  - sudo apt-get install --force-yes libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2
  - npm install -g node-gyp-install jshint istanbul codeclimate-test-reporter
  - node-gyp-install
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git

script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=bded29a8bea5cd83a6764ca7e863950c0f54002e0b4e5537c8df353e196dfb3a codeclimate-test-reporter < coverage/lcov.info

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
